import { runGroqJsonCompletion } from "../services/groqService.js";

export async function analyzeConversation(req, res) {
  try {
    const { conversation } = req.body;

    if (!conversation || conversation.trim().length < 20) {
      return res.status(400).json({ error: "Conversation text is too short." });
    }

    const systemPrompt = `
You are a scam detection AI. Analyze buyer/seller messages (including Roman Urdu and English).

If the conversation involves moving off-platform, demanding advance payment, or pressuring the buyer, calculate a high risk score (70-95).

Return strictly a JSON object with this exact structure:
{
  "riskScore": 85,
  "riskLabel": "High Risk",
  "confidence": 90,
  "confidenceExplanation": "High risk detected due to advance payment request and urgency.",
  "currencyDetected": "PKR",
  "executiveSummary": "Seller is demanding an advance payment of 30,000 PKR before physical inspection and creating artificial urgency.",
  "positiveSignals": [],
  "detectedPatterns": [
    {
      "name": "Advance Payment Request",
      "category": "Payment",
      "severity": "critical",
      "evidence": "Bas abhi advance bhej dein / Kam az kam 30,000 abhi bhej dein",
      "whatItIs": "Seller demands money before goods are inspected or handed over.",
      "whyScammersUseIt": "To secure funds before disappearing without delivering the product.",
      "whyItMatters": "Sending unrecoverable advance payments is the most common marketplace scam.",
      "scoreImpact": -40
    },
    {
      "name": "Artificial Urgency",
      "category": "Urgency",
      "severity": "high",
      "evidence": "Jaldi karein warna doosra buyer confirm kar raha hai",
      "whatItIs": "Pressuring the buyer to decide quickly without thinking.",
      "whyScammersUseIt": "To prevent the buyer from doing due diligence or verification.",
      "whyItMatters": "Forced quick decisions often lead to oversight.",
      "scoreImpact": -25
    }
  ],
  "informationNotVerified": ["Seller identity", "Physical location of laptop"],
  "safetyChecklist": {
    "identityIndependentlyVerified": "no",
    "securePaymentMethodAvailable": "no",
    "pressureFreeConversation": "no",
    "urgencyDetected": "yes",
    "sensitiveInfoRequested": "no",
    "movedOffOriginalPlatform": "yes",
    "advancePaymentRequested": "yes",
    "willingToVerifyClaims": "no"
  },
  "timeline": [
    "Buyer asked to check laptop first",
    "Seller insisted on advance payment of 30,000 PKR",
    "Seller pressured buyer citing another interested party"
  ],
  "riskScoreBreakdown": [
    { "factor": "Advance payment demand", "impact": 40 },
    { "factor": "Artificial pressure tactics", "impact": 25 },
    { "factor": "Refusal/avoidance of in-person check", "impact": 20 }
  ],
  "recommendations": [
    "Do not pay any advance payment.",
    "Only deal in person with Cash on Delivery in a public location."
  ],
  "suggestedQuestions": [
    "Can we meet at a public place so I can inspect and pay on the spot?"
  ],
  "aiTransparencyExplanation": "Evaluated message triggers for advance payment demands and urgency flags.",
  "finalVerdict": "High risk of fraud. Avoid making advance payments.",
  "disclaimer": "This analysis is generated by AI for advisory purposes."
}
`;

    const userPrompt = `Analyze this conversation log (Roman Urdu/English) and output a JSON object:\n\n${conversation}`;

    const reportData = await runGroqJsonCompletion(
      [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      {
        model: "llama-3.1-8b-instant",
        temperature: 0.1,
        maxTokens: 1500,
      }
    );

    const hasAdvance = /advance|bhej|30,000|30000|paisa/i.test(conversation);
    const calculatedScore = typeof reportData.riskScore === "number" && reportData.riskScore > 0 
      ? reportData.riskScore 
      : (hasAdvance ? 85 : 50);

    const sanitizedReport = {
      riskScore: calculatedScore,
      riskLabel: reportData.riskLabel || (calculatedScore >= 70 ? "High Risk" : "Moderate Risk"),
      confidence: typeof reportData.confidence === "number" && reportData.confidence > 0 ? reportData.confidence : 90,
      confidenceExplanation: reportData.confidenceExplanation || "High confidence based on advance payment indicators in chat.",
      currencyDetected: reportData.currencyDetected || "PKR",
      executiveSummary: reportData.executiveSummary || "The seller is requesting advance payment prior to physical product verification.",
      positiveSignals: Array.isArray(reportData.positiveSignals) ? reportData.positiveSignals : [],
      detectedPatterns: Array.isArray(reportData.detectedPatterns) && reportData.detectedPatterns.length > 0
        ? reportData.detectedPatterns
        : [
            {
              name: "Advance Payment Request",
              category: "Payment Risk",
              severity: "high",
              evidence: "Advance payment demanded in chat",
              whatItIs: "Demand for upfront funds.",
              whyScammersUseIt: "To take money before product inspection.",
              whyItMatters: "Unrecoverable deposit risk.",
              scoreImpact: -40
            }
          ],
      informationNotVerified: Array.isArray(reportData.informationNotVerified) ? reportData.informationNotVerified : ["Seller identity"],
      safetyChecklist: {
        identityIndependentlyVerified: reportData.safetyChecklist?.identityIndependentlyVerified || "no",
        securePaymentMethodAvailable: reportData.safetyChecklist?.securePaymentMethodAvailable || "no",
        pressureFreeConversation: reportData.safetyChecklist?.pressureFreeConversation || "no",
        urgencyDetected: reportData.safetyChecklist?.urgencyDetected || "yes",
        sensitiveInfoRequested: reportData.safetyChecklist?.sensitiveInfoRequested || "no",
        movedOffOriginalPlatform: reportData.safetyChecklist?.movedOffOriginalPlatform || "yes",
        advancePaymentRequested: reportData.safetyChecklist?.advancePaymentRequested || "yes",
        willingToVerifyClaims: reportData.safetyChecklist?.willingToVerifyClaims || "no",
      },
      timeline: Array.isArray(reportData.timeline) ? reportData.timeline : ["Buyer asked for inspection", "Seller demanded advance payment"],
      riskScoreBreakdown: Array.isArray(reportData.riskScoreBreakdown) ? reportData.riskScoreBreakdown : [{ factor: "Advance payment required", impact: 40 }],
      recommendations: Array.isArray(reportData.recommendations) ? reportData.recommendations : [
        "Do not send advance money.",
        "Insist on Cash on Delivery in person."
      ],
      suggestedQuestions: Array.isArray(reportData.suggestedQuestions) ? reportData.suggestedQuestions : [
        "Can we deal face to face in a safe public spot?"
      ],
      aiTransparencyExplanation: reportData.aiTransparencyExplanation || "Automated chat fraud analysis.",
      finalVerdict: reportData.finalVerdict || "High Risk - Do not send advance payment.",
      disclaimer: reportData.disclaimer || "AI advisory assessment.",
    };

    // KEY FIX: Wrap in { report: sanitizedReport } so frontend api.ts (data.report) receives the payload!
    return res.status(200).json({ report: sanitizedReport });
  } catch (error) {
    console.error("[Conversation Controller Error]:", error);
    return res.status(500).json({ error: "Failed to analyze conversation." });
  }
}